DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS Value;

CREATE TABLE IF NOT EXISTS Area (
	areaID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	area VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Value (
	valueID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	areaID INTEGER NOT NULL,
	applicableFor DATE NOT NULL,
	calorificValue DECIMAL(10) NOT NULL,
	FOREIGN KEY (areaID) REFERENCES Area(areaID) ON UPDATE CASCADE ON DELETE CASCADE
);